# Generated by Django 3.2 on 2022-05-24 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255, unique=True, verbose_name='식품명')),
                ('product_name', models.CharField(max_length=255, unique=True, verbose_name='상품명')),
                ('main_cat', models.CharField(max_length=255, unique=True, verbose_name='식품대분류')),
                ('sub_cat', models.CharField(max_length=255, unique=True, verbose_name='식품상세분류')),
                ('energy', models.PositiveIntegerField(default=0, verbose_name='에너지(kcal)')),
                ('carb', models.PositiveIntegerField(default=0, verbose_name='탄수화물(g)')),
                ('protein', models.PositiveIntegerField(default=0, verbose_name='단백질(g)')),
                ('fat', models.PositiveIntegerField(default=0, verbose_name='지방(g)')),
                ('sugar', models.PositiveIntegerField(default=0, verbose_name='당류(g)')),
                ('fiber', models.PositiveIntegerField(default=0, verbose_name='식이섬유(g)')),
                ('sodium', models.PositiveIntegerField(default=0, verbose_name='나트륨(mg)')),
            ],
        ),
        migrations.CreateModel(
            name='FoodImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_image', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='이미지 주소')),
                ('upload_date', models.DateTimeField(auto_now=True, verbose_name='업로드 날짜')),
                ('uploader', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
