# Generated by Django 3.2 on 2022-05-24 14:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodimage',
            name='uploader',
        ),
        migrations.AddField(
            model_name='foodimage',
            name='uploader',
            field=models.ManyToManyField(null=True, related_name='food', to=settings.AUTH_USER_MODEL),
        ),
    ]
