# Generated by Django 3.2 on 2022-05-24 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodapp', '0002_auto_20220524_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodimage',
            name='uploader',
        ),
        migrations.AddField(
            model_name='foodimage',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food', to=settings.AUTH_USER_MODEL),
        ),
    ]
