# Generated by Django 3.2 on 2022-05-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_auto_20220524_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='carb',
            field=models.FloatField(default=0, verbose_name='탄수화물(g)'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='energy',
            field=models.FloatField(default=0, verbose_name='에너지(kcal)'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='fat',
            field=models.FloatField(default=0, verbose_name='지방(g)'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='fiber',
            field=models.FloatField(default=0, verbose_name='식이섬유(g)'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='protein',
            field=models.FloatField(default=0, verbose_name='단백질(g)'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sodium',
            field=models.FloatField(default=0, verbose_name='나트륨(mg)'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sugar',
            field=models.FloatField(default=0, verbose_name='당류(g)'),
        ),
    ]
