# Generated by Django 3.2 on 2022-05-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_auto_20220525_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='main_cat',
            field=models.CharField(max_length=255, verbose_name='식품대분류'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='product_name',
            field=models.CharField(max_length=255, verbose_name='상품명'),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sub_cat',
            field=models.CharField(max_length=255, verbose_name='식품상세분류'),
        ),
    ]
