# Generated by Django 3.2 on 2022-05-22 13:58

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='키(cm)')),
                ('weight', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='몸무게(kg)')),
                ('age', models.PositiveIntegerField(verbose_name='나이')),
                ('gender', models.CharField(choices=[('M', '남성'), ('W', '여성')], max_length=1, verbose_name='성별')),
                ('activity', models.CharField(choices=[('sedentary', '거의 운동 하지 않음음'), ('slightly', '가벼운 활동(주 1~3회)'), ('moderately', '보통 수준(주 3~5회)'), ('very', '적극적으로 운동(주 6~7회)'), ('extra', '매우 적극적으로 운동(주 6~7회)')], max_length=255, verbose_name='활동 및 운동 수준')),
                ('bmr', models.PositiveIntegerField(verbose_name='기초대사량')),
                ('caloric_burn', models.PositiveIntegerField(verbose_name='활동대사량')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
